---
title: "Quantifying the Impacts of Building Energy Efficiency Retrofits and Nature Exposure on Chronic Student Absenteeism"
author: "Devan Cantrell Addison-Turner, Yingjie Li, Anthony Dylan Kinslow II, Rishee Kumar Jain, and Gretchen Cara Daily"
date: "2024-06-27"
output: html_document
editor_options: 
  chunk_output_type: inline
---


# Setup
```{r}

### To clear your environment
remove(list = ls())

#Get working directory and file path information, then set for working environment in the current R session.
getwd()
# setwd('path')
```

```{r include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


## Packages --------------------------------------------------------------------
library(readr)
library(readxl)
library(dplyr)
library(tidyverse)


### --- viz ----
library(ggplot2)
library(viridis)



```


# Treatment Analysis for 3 Policy Interventions in K-12 schools 

## EE - comb 1
```{r}
# Total number of Treatments for K-12 Schools in each policy intervention/scenario

#Read individual data file to obtain the total counts of treatments across each scenario and interventions 
#including subset of EE retrofit
#for the following variables (i) retrofit, (ii) ndvi_median_binary, (iii) retrofit_and_ndvi

#Group by the unique Unique County, District, School Code (CDS Code)

#Complete Dataset with All Energy Efficiency Retrofits in K-12 schools
Treatment_Count_Data_All <- read_csv("./data/Treatment_Count_Data_All_coord.csv", show_col_types = F)

# Total Number of K-Schools analyzed by the Unique County, District, School Code (CDS Code)
length(unique(Treatment_Count_Data_All$CDSCode))


#calculate total number of interventions in each scenario by the unique K-12 school
treatment_count_by_scenario <- Treatment_Count_Data_All %>% 
  select(retrofit, ndvi_median_binary, retrofit_and_ndvi) %>% 
  summarise_if(is.numeric, list(sum = ~sum(., na.rm = TRUE)))


## Subset Data by 4 types of Energy Efficiency Retrofits

#1. Lighting 
#2. HVAC
#3. Building Envelope
#4. Pumps, Motors, & Drives
```


### with scenario
```{r}
Treatment_Count_df <- Treatment_Count_Data_All %>% 
  filter(!is.na(EE_Retrofit_Type)) %>%
  select(EEM, EE_Retrofit_Type, retrofit, ndvi_median_binary, retrofit_and_ndvi) %>% 
  pivot_longer(cols = 3:ncol(.), names_to = 'Scenario') %>%
  mutate(treatment_control = ifelse(value==1, 'T', 'C'),
         treatment_control = as.factor(treatment_control))


## by Retrofit Type and by scenario
count_df_byScenario_byRetrofitType <- Treatment_Count_df %>%
  group_by(EE_Retrofit_Type, Scenario, treatment_control) %>% 
  count() %>%
  mutate(Scenario = factor(Scenario, 
                           levels = c("retrofit", 
                                      "ndvi_median_binary", 
                                      "retrofit_and_ndvi"), 
                           labels = c( 'Scenario 1: EE Retrofit', 
                                       'Scenario 2: Nature Exposure',
                                       'Scenario 3: EE Retrofit and Nature Exposure'))
         ) %>%
  mutate(Type = paste0(EE_Retrofit_Type, ' - ', treatment_control)) %>%
  as.data.frame()

# str(count_df_byScenario_byRetrofitType)
```



```{r}
## plot
count_df_byScenario_byRetrofitType %>%
  filter(!is.na(EE_Retrofit_Type)) %>%
  ggplot(., aes(fill = Scenario, x = Type, y = n)) +
  geom_bar(
    aes(
      # color = treatment_control,
      alpha = treatment_control),
    position = "stack",
    stat = "identity") +
  # scale_color_manual(values = c('white', 'black')) +
  scale_alpha_manual(values = c(.5, 1)) +
  guides(alpha = "none") +
  # Add text labels
  geom_text(aes(label = ifelse(n >= 60, n, "")),
            position = position_stack(vjust = 0.5), # Center labels in the stack
            color = "black") +                     # Change label color to white
  labs(x = "Energy Efficiency Retrofit", y = "Number of K-12 Schools", title = "Intervention Groups in California, USA K-12 Schools") +
  coord_flip() +
  theme_bw() +
  theme(legend.position = c(.7,.15)) +
  # scale_fill_discrete(labels=c('Scenario 2: Nature Exposure', 'Scenario 1: EE Retrofit', 'Scenario 3: EE Retrofit and Nature Exposure')) +
  theme(plot.title = element_text(hjust = 0.5))  # Center ggplot title

f <- paste0('./figures/', 'treatment_count_comb1.png')
ggsave(filename = f, plot = last_plot(), width = 7, height = 5, units = "in", dpi = 300)

```



### without scenario


#### by type and intervention 

```{r}
treatment_count_noScenario_byRetrofitType <- Treatment_Count_Data_All %>% 
  select(EE_Retrofit_Type, retrofit, ndvi_median_binary, retrofit_and_ndvi) %>% 
  pivot_longer(cols = 2:ncol(.), names_to = 'Scenario') %>%
  group_by(EE_Retrofit_Type, value) %>% 
  count() %>%
  mutate(treatment_control = ifelse(value==1, 'T', 'C'),
         treatment_control = as.factor(treatment_control)
         ) %>%
  mutate(Type = paste0(EE_Retrofit_Type, ' - ', treatment_control)) %>%
  as.data.frame()

```



```{r}
## plot
treatment_count_noScenario_byRetrofitType %>%
  filter(!is.na(EE_Retrofit_Type)) %>%
  ggplot(., aes(x = Type, y = n)) +
  geom_bar(
    aes(alpha = treatment_control),
    position = "stack",
    stat = "identity") +
  # scale_color_manual(values = c('white', 'black')) +
  scale_alpha_manual(values = c(.5, 1)) +
  guides(alpha = "none") +
  # Add text labels
  geom_text(aes(label = ifelse(n >= 60, n, "")),
            position = position_stack(vjust = 0.5), # Center labels in the stack
            color = "black") +                     # Change label color to white
  labs(x = "Energy Efficiency Retrofit", 
       y = "Number of K-12 Schools", 
       title = "Intervention Groups in California, USA K-12 Schools") +
  coord_flip() +
  theme_bw() +
  theme(legend.position = c(.7,.15)) +
  # scale_fill_discrete(labels=c('Scenario 2: Nature Exposure', 'Scenario 1: EE Retrofit', 'Scenario 3: EE Retrofit and Nature Exposure')) +
  theme(plot.title = element_text(hjust = 0.5))  # Center ggplot title

f <- paste0('./figures/', 'treatment_count_comb1_noScenario.png')
ggsave(filename = f, plot = last_plot(), width = 7, height = 5, units = "in", dpi = 300)
```


#### by intervention, Retrofit Type, and EEM

```{r}
## by Retrofit Type and by EEM
count_df_byEEM <- Treatment_Count_df %>% 
  group_by(EE_Retrofit_Type, EEM, treatment_control) %>% 
  count() %>%
  mutate(group = paste0(EEM, ' - ', treatment_control))


count_df_byEEM %>%
  ggplot(., aes(x = group, 
                fill = EE_Retrofit_Type,
                y = n)) +
  geom_bar(
    aes(alpha = treatment_control),
    position = "stack",
    stat = "identity") +
  scale_alpha_manual(values = c(.5, 1)) +
  guides(alpha = "none") +

  geom_text(aes(label = ifelse(n >= 0, n, "")),
            # position = position_stack(vjust = 0), # Center labels in the stack
            position = position_dodge(width = 1),
            hjust = -0.1,
            inherit.aes = TRUE,
            color = "black") +                      # Change label color to white
  scale_y_continuous(expand = expansion(mult = c(0.02, 0.1))) +  # Add 2% left and 10% space on the right
  
  labs(x = "Energy Efficiency Measure", 
       y = "Number of K-12 Schools", 
       title = "Intervention Groups in California, USA K-12 Schools") +
  coord_flip() +
  theme_bw() +
  theme(legend.position = c(0.75, 0.1),
        legend.background=element_blank()) +
  theme(plot.title = element_text(hjust = 0.5))  # Center ggplot title

f <- paste0('./figures/', 'treatment_count_comb1_byEEM.png')
ggsave(filename = f, plot = last_plot(), width = 7, height = 9, units = "in", dpi = 300)

```



#### by intervention, Retrofit Type

```{r}
## plot
comb1 <- treatment_count_noScenario_byRetrofitType %>%
  filter(!is.na(EE_Retrofit_Type)) %>%
  arrange((n)) %>% 
  mutate(
    EE_Retrofit_Type = factor(EE_Retrofit_Type, levels = unique(EE_Retrofit_Type))
  ) %>%
  select(-Type, -value)

# The palette with grey:
cbPalette <- c("#F0E442", "#56B4E9", "#009E73", "#CC79A7")


comb1 %>%
  ggplot(., aes(x = treatment_control, 
                fill = EE_Retrofit_Type,
                y = n)) +
  geom_bar(
    # aes(
    #   # alpha = treatment_control,
    #   fill = EE_Retrofit_Type),
    position = "stack",
    stat = "identity") +
  # scale_alpha_manual(values = c(.5, 1)) +
  # scale_fill_brewer(palette = 'Paired') +
  scale_fill_manual(values=rev(cbPalette)) +
  # guides(alpha = "none") +
  # Add text labels
  geom_text(aes(label = ifelse(n >= 10, n, "")),
            position = position_stack(vjust = 0.5), # Center labels in the stack
            color = "black") +                      # Change label color to white
  labs(x = "Interventions", 
       y = "Number of K-12 Schools", 
       title = "Intervention Groups in California, USA K-12 Schools") +
  coord_flip() +
  theme_bw() +
  theme(legend.position = c(0.85, 0.2),
        legend.background=element_blank()) +
  theme(plot.title = element_text(hjust = 0.5))  # Center ggplot title

f <- paste0('./figures/', 'treatment_count_comb1_noScenario_byEE.png')
ggsave(filename = f, plot = last_plot(), width = 7, height = 5, units = "in", dpi = 300)
```


## EE - comb 2

```{r}
comb <- count_df_byScenario_byRetrofitType %>%
  filter(!is.na(EE_Retrofit_Type)) %>%
  as.data.frame()

# Get all unique 2-type combinations
type_pairs <- combn(unique(comb$EE_Retrofit_Type), 2, simplify = FALSE)

# Calculate total count for each pair and feature
library(purrr)

comb2 <- map_dfr(type_pairs, ~ {
  comb %>%
    filter(EE_Retrofit_Type %in% .x) %>%           # Keep rows with the current pair of types
    group_by(Scenario, treatment_control) %>%              # Group by feature
    summarise(n = sum(n, na.rm = T)) %>%  # Sum count for the group
    mutate(combination = paste(.x, collapse = " & "))  # Add combination label
}) %>%
  as.data.frame() %>%
  mutate(Type = paste0(combination, ' - ', treatment_control))
```


```{r}

comb2 %>%
  ggplot(., aes(fill = Scenario, x = Type, y = n)) +
  geom_bar(
    aes(
      # color = treatment_control,
      alpha = treatment_control),
    position = "stack",
    stat = "identity") +
  # scale_color_manual(values = c('white', 'black')) +
  scale_alpha_manual(values = c(.5, 1)) +
  guides(alpha = "none") +
  # Add text labels
  geom_text(aes(label = ifelse(n >= 60, n, "")),
            position = position_stack(vjust = 0.5), # Center labels in the stack
            color = "black") +                     # Change label color to white
  labs(x = "Energy Efficiency Retrofit", y = "Number of K-12 Schools", title = "Intervention Groups in California, USA K-12 Schools") +
  coord_flip() +
  theme_bw() +
  theme(legend.position = c(0.7, 0.08), 
        legend.key.height= unit(0.5, 'cm'),
        legend.key.width= unit(0.5, 'cm'),
        legend.background=element_blank()) +
  # scale_fill_discrete(labels=c('Scenario 2: Nature Exposure', 'Scenario 1: EE Retrofit', 'Scenario 3: EE Retrofit and Nature Exposure')) +
  theme(plot.title = element_text(hjust = 0.5))  # Center ggplot title

f <- paste0('./figures/', 'treatment_count_comb2.png')
ggsave(filename = f, plot = last_plot(), width = 8, height = 6, units = "in", dpi = 300)
```



## EE - comb 3

```{r}

# Get all unique 2-type combinations
type_pairs <- combn(unique(comb$EE_Retrofit_Type), 3, simplify = FALSE)

# Calculate total count for each pair and feature
comb3 <- map_dfr(type_pairs, ~ {
  comb %>%
    filter(EE_Retrofit_Type %in% .x) %>%           # Keep rows with the current pair of types
    group_by(Scenario, treatment_control) %>%              # Group by feature
    summarise(n = sum(n, na.rm = T)) %>%  # Sum count for the group
    mutate(combination = paste(.x, collapse = " & "))  # Add combination label
}) %>%
  as.data.frame() %>%
  mutate(Type = paste0(combination, ' - ', treatment_control))
```


```{r}

comb3 %>%
  ggplot(., aes(fill = Scenario, x = Type, y = n)) +
  geom_bar(
    aes(
      # color = treatment_control,
      alpha = treatment_control),
    position = "stack",
    stat = "identity") +
  # scale_color_manual(values = c('white', 'black')) +
  scale_alpha_manual(values = c(.5, 1)) +
  guides(alpha = "none") +
  # Add text labels
  geom_text(aes(label = ifelse(n >= 60, n, "")),
            position = position_stack(vjust = 0.5), # Center labels in the stack
            color = "black") +                     # Change label color to white
  labs(x = "Energy Efficiency Retrofit", y = "Number of K-12 Schools", title = "Intervention Groups in California, USA K-12 Schools") +
  coord_flip() +
  theme_bw() +
  theme(legend.position = c(0.7, 0.4), 
        legend.key.height= unit(0.5, 'cm'),
        legend.key.width= unit(0.5, 'cm'),
        legend.background=element_blank()) +
  # scale_fill_discrete(labels=c('Scenario 2: Nature Exposure', 'Scenario 1: EE Retrofit', 'Scenario 3: EE Retrofit and Nature Exposure')) +
  theme(plot.title = element_text(hjust = 0.5))  # Center ggplot title

f <- paste0('./figures/', 'treatment_count_comb3.png')
ggsave(filename = f, plot = last_plot(), width = 8.5, height = 6, units = "in", dpi = 300)
```




## EE - comb 4

```{r}

# Get all unique 2-type combinations
type_pairs <- combn(unique(comb$EE_Retrofit_Type), 4, simplify = FALSE)

# Calculate total count for each pair and feature
comb4 <- map_dfr(type_pairs, ~ {
  comb %>%
    filter(EE_Retrofit_Type %in% .x) %>%           # Keep rows with the current pair of types
    group_by(Scenario, treatment_control) %>%              # Group by feature
    summarise(n = sum(n, na.rm = T)) %>%  # Sum count for the group
    mutate(combination = paste(.x, collapse = " & "))  # Add combination label
}) %>%
  as.data.frame() %>%
  mutate(Type = paste0('All 4 types of EE Retrofits', ' - ', treatment_control))
```


```{r}

comb4 %>%
  ggplot(., aes(fill = Scenario, x = Type, y = n)) +
  geom_bar(
    aes(
      alpha = treatment_control),
      position = "stack",
      stat = "identity") +
  # scale_color_manual(values = c('white', 'black')) +
  scale_alpha_manual(values = c(.5, 1)) +
  guides(alpha = "none") +
  # Add text labels
  geom_text(aes(label = ifelse(n >= 60, n, "")),
            position = position_stack(vjust = 0.5), # Center labels in the stack
            color = "black") +                     # Change label color to white
  labs(x = "Energy Efficiency Retrofit", y = "Number of K-12 Schools", title = "Intervention Groups in California, USA K-12 Schools") +
  coord_flip() +
  theme_bw() +
  scale_x_discrete(expand = expansion(mult = c(1.5, 0.6))) +  # Add 150% space at the bottom
  # scale_x_discrete(expand = c(2, 0)) +  # Add 10% space at the top
  theme(legend.position = c(0.7, 0.15), 
        legend.key.height= unit(0.5, 'cm'),
        legend.key.width= unit(0.5, 'cm'),
        legend.background=element_blank()) +
  # scale_fill_discrete(labels=c('Scenario 2: Nature Exposure', 'Scenario 1: EE Retrofit', 'Scenario 3: EE Retrofit and Nature Exposure')) +
  theme(plot.title = element_text(hjust = 0.5))  # Center ggplot title

f <- paste0('./figures/', 'treatment_count_comb4.png')
ggsave(filename = f, plot = last_plot(), width = 8, height = 4, units = "in", dpi = 300)
```





```{r}
library(readr)
library(readxl)
library(dplyr)

Treatment_Count_Data_All_coord <- read_xlsx("Treatment_Count_Data_All_coord.xlsx")

#Dual EE Sub-System Retrofits
Treatment_Count_subLH <- subset(Treatment_Count_Data_All_coord, EE_Retrofit_Type == "Lighting" | EE_Retrofit_Type == "HVAC")
Treatment_Count_subLB <- subset(Treatment_Count_Data_All_coord, EE_Retrofit_Type == "Lighting" | EE_Retrofit_Type == "Building_Envelope")
Treatment_Count_subLP <- subset(Treatment_Count_Data_All_coord, EE_Retrofit_Type == "Lighting" | EE_Retrofit_Type == "Pumps_Motors_Drives")
Treatment_Count_subHB <- subset(Treatment_Count_Data_All_coord, EE_Retrofit_Type == "HVAC" | EE_Retrofit_Type == "Building_Envelope")
Treatment_Count_subHP <- subset(Treatment_Count_Data_All_coord, EE_Retrofit_Type == "HVAC" | EE_Retrofit_Type == "Pumps_Motors_Drives")
Treatment_Count_subBP <- subset(Treatment_Count_Data_All_coord, EE_Retrofit_Type == "Building_Envelope" | EE_Retrofit_Type == "Pumps_Motors_Drives")

#Triple EE Sub-System Retrofits
Treatment_Count_subLHB <- subset(Treatment_Count_Data_All_coord, EE_Retrofit_Type == "Lighting" | EE_Retrofit_Type == "HVAC" | EE_Retrofit_Type == "Building_Envelope")
Treatment_Count_subLHP <- subset(Treatment_Count_Data_All_coord, EE_Retrofit_Type == "Lighting" | EE_Retrofit_Type == "HVAC" | EE_Retrofit_Type == "Pumps_Motors_Drives")
Treatment_Count_subHBP <- subset(Treatment_Count_Data_All_coord, EE_Retrofit_Type == "HVAC" | EE_Retrofit_Type == "Building_Envelope" | EE_Retrofit_Type == "Pumps_Motors_Drives")
Treatment_Count_subBLP <- subset(Treatment_Count_Data_All_coord, EE_Retrofit_Type == "Building_Envelope" | EE_Retrofit_Type == "Lighting | EE_Retrofit_Type == Pumps_Motors_Drives")

#Scenario 1: All Energy Efficiency (EE) Retrofits in K-12 Schools 
Treatment_Count_AllS1 <- Treatment_Count_Data_All_coord %>% group_by(retrofit) %>% 
  summarize(count_distinct = n_distinct(CDSCode))

#Scenario 1: EE Sub-System Retrofits in K-12 Schools 
Treatment_Count_AllS1_Sub <- Treatment_Count_Data_All_coord %>% group_by(retrofit, EE_Retrofit_Type) %>% 
  summarize(count_distinct = n_distinct(CDSCode))

## Dual EE Sub-System Retrofits

#Scenario 1LH: Lighting + HVAC in K-12 Schools 
Treatment_Count_S1_SubLH <-Treatment_Count_subLH %>% group_by(retrofit) %>% 
  summarize(count_distinct = n_distinct(CDSCode))

#Scenario 1LB: Lighting + Building Envelope in K-12 Schools 
Treatment_Count_S1_SubLB <-Treatment_Count_subLB %>% group_by(retrofit) %>% 
  summarize(count_distinct = n_distinct(CDSCode))

#Scenario 1LP: Lighting + Pumps in K-12 Schools 
Treatment_Count_S1_SubLP <-Treatment_Count_subLP %>% group_by(retrofit) %>% 
  summarize(count_distinct = n_distinct(CDSCode))

#Scenario 1HB: HVAC + Building Envelope in K-12 Schools 
Treatment_Count_S1_SubHB <-Treatment_Count_subHB %>% group_by(retrofit) %>% 
  summarize(count_distinct = n_distinct(CDSCode))

#Scenario 1HP: HVAC + Pumps, Motor, & Drives in K-12 Schools 
Treatment_Count_S1_SubHP <-Treatment_Count_subHP %>% group_by(retrofit) %>% 
  summarize(count_distinct = n_distinct(CDSCode))

#Scenario 1BP: Building Envelope + Pumps, Motors, & Drives in K-12 Schools 
Treatment_Count_S1_SubBP <-Treatment_Count_subBP %>% group_by(retrofit) %>% 
  summarize(count_distinct = n_distinct(CDSCode))


## Triple EE Sub-System Retrofits
#Scenario 1LHB: Lighting + HVAC + Building Envelope in K-12 Schools 
Treatment_Count_S1_SubLHB <-Treatment_Count_subLHB %>% group_by(retrofit) %>% 
  summarize(count_distinct = n_distinct(CDSCode))

#Scenario 1LHP: Lighting + HVAC + Pumps, Motors, & Drives in K-12 Schools 
Treatment_Count_S1_SubLHP <-Treatment_Count_subLHP %>% group_by(retrofit) %>% 
  summarize(count_distinct = n_distinct(CDSCode))

#Scenario 1HBP: HVAC + Building Envelope + Pumps, Motor, & Drives in K-12 Schools 
Treatment_Count_S1_SubHBP <-Treatment_Count_subHBP %>% group_by(retrofit) %>% 
  summarize(count_distinct = n_distinct(CDSCode))

#Scenario 1BLP: Building Envelope + Lighting + Pumps, Motors, & Drives in K-12 Schools 
Treatment_Count_S1_SubBLP <-Treatment_Count_subBLP %>% group_by(retrofit) %>% 
  summarize(count_distinct = n_distinct(CDSCode))

Scenario 2: Nature Exposure in K-12 Schools 
Treatment_Count_All_S2<- Treatment_Count_Data_All_coord %>% group_by(ndvi_median_binary) %>% 
  summarize(count_distinct = n_distinct(CDSCode))

Scenario 3: All Energy Efficiency Retrofits and Nature Exposure in K-12 Schools 
Treatment_Count_All_S3 <- Treatment_Count_Data_All_coord %>% group_by(retrofit_and_ndvi) %>% 
  summarize(count_distinct = n_distinct(CDSCode))

Scenario 3: Energy Efficiency (EE) Sub-System Retrofits and Nature Exposure in K-12 Schools 
Treatment_Count_S3_Sub <- Treatment_Count_Data_All_coord %>% group_by(retrofit_and_ndvi, EE_Retrofit_Type) %>% 
  summarize(count_distinct = n_distinct(CDSCode))

#Dual EE Sub-System Retrofits and Nature Exposure

#Scenario 3LH: Lighting + HVAC + Nature Exposure in K-12 Schools
Treatment_Count_S3_SubLH <-Treatment_Count_subLH %>% group_by(retrofit_and_ndvi) %>% 
  summarize(count_distinct = n_distinct(CDSCode))

#Scenario 3LB: Lighting + Building Envelope + Nature Exposure in K-12 Schools
Treatment_Count_S3_SubLB <-Treatment_Count_subLB %>% group_by(retrofit_and_ndvi) %>% 
  summarize(count_distinct = n_distinct(CDSCode))

#Scenario 3LP: Lighting + Pumps, Motors, & Drives + Nature Exposure in K-12 Schools
Treatment_Count_S3_SubLP <-Treatment_Count_subLP %>% group_by(retrofit_and_ndvi) %>% 
  summarize(count_distinct = n_distinct(CDSCode))

#Scenario 3HB: HVAC + Building Envelope + Nature Exposure in K-12 Schools
Treatment_Count_S3_SubHB <-Treatment_Count_subHB %>% group_by(retrofit_and_ndvi) %>% 
  summarize(count_distinct = n_distinct(CDSCode))

#Scenario 3HP: HVAC + Pumps, Motor, & Drives + Nature Exposure in K-12 Schools
Treatment_Count_S3_SubHP <-Treatment_Count_subHP %>% group_by(retrofit_and_ndvi) %>% 
  summarize(count_distinct = n_distinct(CDSCode))

#Scenario 3BP: Building Envelope + Pumps, Motors, & Drives + Nature Exposure in K-12 Schools
Treatment_Count_S3_SubBP <-Treatment_Count_subBP %>% group_by(retrofit_and_ndvi) %>% 
  summarize(count_distinct = n_distinct(CDSCode))

#Triple EE Sub-System Retrofits and Nature Exposure

#Scenario 3LHB: Lighting + HVAC + Building Envelope + Nature Exposure in K-12 Schools
Treatment_Count_S3_SubLHB <-Treatment_Count_subLHB %>% group_by(retrofit_and_ndvi) %>% 
  summarize(count_distinct = n_distinct(CDSCode))

#Scenario 3LHP: Lighting + HVAC + Pumps, Motors, and Drives + Nature Exposure in K-12 Schools
Treatment_Count_S3_SubLHP <-Treatment_Count_subLHP %>% group_by(retrofit_and_ndvi) %>% 
  summarize(count_distinct = n_distinct(CDSCode))

#Scenario 3HBP: HVAC + Building Envelope + Pumps, Motor, & Drives + Nature Exposure in K-12 Schools
Treatment_Count_S3_SubHBP <-Treatment_Count_subHBP %>% group_by(retrofit_and_ndvi) %>% 
  summarize(count_distinct = n_distinct(CDSCode))

#Scenario 3BLP: Building Envelope + Lighting + Pumps, Motors, & Drives + Nature Exposure in K-12 Schools
Treatment_Count_S3_SubBLP <-Treatment_Count_subBLP %>% group_by(retrofit_and_ndvi) %>% 
  summarize(count_distinct = n_distinct(CDSCode))
```


